# Minimum Yaml start file will be used as start template for build the complete azure-pipeline.yml in config environment Directory
# Either add variables to your Azure DevOps Pipeline or change the variable to parameters or fill in when run
name: "PackerImageGallerySample"
parameters:
- name: Subscription
  type: string
  default: $(Subscription)
- name: SubscriptionId
  type: string
  default: $(SubscriptionId)
- name: ResourceGroupName
  type: string
  default: $(ResourceGroupName)
- name: KeyVaultName
  type: string
  default: $(KeyVaultName)
- name: PackerServicePrincipale
  type: string
  default: $(PackerServicePrincipale)
- name: gallery_name
  type: string
  default: $(gallery_name)
- name: image_name
  type: string
  default: $(image_name)
- name: image_version
  type: string
  default: $(image_version)
- name: osType
  type: string
  default: $(osType)


trigger: none

variables:

  # Agent VM image name
  vmImageName: 'vs2017-win2016'

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: Hosted VS2017
      demands: 
      - msbuild

    steps:
      - task: PublishPipelineArtifact@1
        inputs:
          path: $(System.DefaultWorkingDirectory)
          artifact: Sources
        
- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      name: Hosted VS2017
    environment: 'development'
    

    strategy:
      runOnce:
        deploy:

          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: Sources
          
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: ${{ parameters.Subscription }}
              ScriptType: 'FilePath'
              ScriptPath: '$(Pipeline.Workspace)/CreateImagePacker/linuxImage/createImageGalleryRunPacker.ps1'
              scriptArguments:
                -subscriptionID  ${{ parameters.SubscriptionId }}  -ResourceGroupName  ${{ parameters.ResourceGroupName }} -KeyVaultName  ${{ parameters.KeyVaultName }}  -PackerServicePrincipale  ${{ parameters.PackerServicePrincipale }} -gallery_name  ${{ parameters.gallery_name }} -image_version  ${{ parameters.image_version }} -osType  ${{ parameters.osType }} 
              azurePowerShellVersion: 'LatestVersion'
              pwsh: true' 
